name: java_workflow

on:
 push:


jobs:
  build_and_test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run
      run: |
       cd ./src/main
       java App.java
